package forum.domain.lobby.model

import forum.routes.common.AccountData

/**
 * Model for the lobby page `/`.
 * This mostly contains dummy data.
 *
 * @property account Optional [AccountData] of the user.
 * @property time System time to give a sense that the server is operating.
 * @property bias Demonstrate a simple string data generated by the user.
 *                Particularly, it gives you a random member as your bias.
 */
data class LobbyModel(
    val account: AccountData?,
    val time: String,
    val bias: String
)
